// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7aV-ug8cSLUCJG5CqaaMVO5oPgViu10',
    appId: '1:484998251170:web:bdbf04ddf58ee78c954dfb',
    messagingSenderId: '484998251170',
    projectId: 'book-store-app-291',
    authDomain: 'book-store-app-291.firebaseapp.com',
    databaseURL:
        'https://book-store-app-291-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-store-app-291.appspot.com',
    measurementId: 'G-YW0KVCSLH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZA5MxzzcTlMObKvN6omJeLHsLJfo1GM',
    appId: '1:484998251170:android:f0db595777a80f35954dfb',
    messagingSenderId: '484998251170',
    projectId: 'book-store-app-291',
    databaseURL:
        'https://book-store-app-291-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-store-app-291.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQi9U0YkgdZqXEHa1mC6trFFNHBudZM3w',
    appId: '1:484998251170:ios:4cff3cab9d9c12eb954dfb',
    messagingSenderId: '484998251170',
    projectId: 'book-store-app-291',
    databaseURL:
        'https://book-store-app-291-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-store-app-291.appspot.com',
    iosClientId:
        '484998251170-1akg66ig26luidoi82gufbkgj4fkk4tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQi9U0YkgdZqXEHa1mC6trFFNHBudZM3w',
    appId: '1:484998251170:ios:197d37d52ff224b5954dfb',
    messagingSenderId: '484998251170',
    projectId: 'book-store-app-291',
    databaseURL:
        'https://book-store-app-291-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-store-app-291.appspot.com',
    iosClientId:
        '484998251170-19tc28i9niigqo8vecudojp378qlo4vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstoreapp291',
  );
}
